### PR TITLE
fix(computer_use): make bash tool timeout work on Python 3.9-3.10

### PR DESCRIPTION
**Pull request by endolith**
## Background

`_BashSession.run` in `interpreter/computer_use/tools/bash.py` reads process output until a sentinel using `asyncio.timeout(...)` inside a `try` block.

## Problem

`asyncio.timeout` was added in Python 3.11, but the package declares `python = ">=3.9,<4"` in `pyproject.toml` and CI runs unit tests on Python 3.10. On 3.9/3.10, executing a command through the bash tool crashed with `AttributeError: module 'asyncio' has no attribute 'timeout'` — the run path was completely broken on those supported versions.

## Visible symptoms

- Running the bash tool on Python 3.9 or 3.10 raises `AttributeError` at `bash.py:85` as soon as a command is executed.
- CodeRabbit flagged the version-gated skips added in #172 as hiding this runtime failure.

## What this PR changes

- Replaces `asyncio.timeout` with `asyncio.wait_for` around a small helper coroutine (`_read_until_sentinel`) that reads until the sentinel, matching the timeout pattern already used in `interpreter/computer_use/tools/run.py:29`.
- `asyncio.wait_for` raises `asyncio.TimeoutError` on all supported Python versions (3.9–3.14), so the existing `except asyncio.TimeoutError` path is unchanged in behavior.
- Removes the two `skipif(sys.version_info < (3, 11))` markers added in #172; the timeout test now patches `asyncio.wait_for` instead of `asyncio.timeout`, so the run-path tests execute on every supported version.

## Tests

- `tests/computer_use/tools/test_bash.py`: skips removed, `test_bash_session_run_timeout_marks_session_stale` updated to patch `asyncio.wait_for`; all 14 tests pass locally on Python 3.12.
- Full unit suite (`pytest -m "not integration"`): 408 passed, 31 skipped, 12 deselected, 6 subtests.

## Related work

- Stacked on #172 (`feat/test-computer-use-bash-tool`), which adds the bash tool tests and originally gated the run tests on 3.11+.

### CODE REVIEW

**Comment by endolith** [comment]
3.9 support was removed, 3.10 support will be removed, and this tests the broken Anthropic computer use API which will likely also be removed.
